spring:
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: midas
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    platform: h2

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 33400

general:
  kafka-topic: "transaction"
  incentive-api-url: "http://localhost:8080/incentive"
